# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

# update your app name
app = 'gigapi-changeme'

# update your region of choice
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  image = "ghcr.io/gigapi/gigapi:latest"

[env]
  GIGAPI_ROOT = '/data'

[mounts]
  source = "gigapi_data"
  destination = "/data"

[http_service]
  internal_port = 7971
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 7971
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[services]]
  internal_port = 8082
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "8082"

  [services.ports.tls_options]
    alpn = ["h2"]

# adjust memory, cpu to your needs
[[vm]]
  memory = '512mb' 
  cpu_kind = 'shared'
  cpus = 1
