# Global Telegraf Configuration
[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

# Input Plugins - Collecting System Metrics
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.system]]


[[outputs.influxdb]]
  urls = ["http://gigapi:7971"]
  database = "telegraf"
  skip_database_creation = true
  exclude_retention_policy_tag = true
  exclude_database_tag = true
  content_encoding = "identity"
  namepass = ["cpu", "mem", "disk", "system"]