name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      minio:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
        options: --name minio-server
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Build GigAPI AIO
      run: |
        go mod tidy
        CGO_ENABLED=1 go build -o gigapi .

    - name: Run tests (local)
      continue-on-error: false
      run: |
        mkdir -p ./data
        go test -v ./...
      env:
        GIGAPI_ROOT: "/data"
        GIGAPI_LAYERS_0_NAME: default
        GIGAPI_LAYERS_0_TYPE: fs
        GIGAPI_LAYERS_0_URL: "file:///data"
        GIGAPI_ENABLED: true
        GIGAPI_MERGE_TIMEOUT_S: 10
        
    - name: Run tests (redis)
      continue-on-error: false
      run: |
        mkdir -p ./data-redis
        go test -v ./...
      env:
        GIGAPI_ROOT: "/data-redis"
        GIGAPI_LAYERS_0_NAME: default
        GIGAPI_LAYERS_0_TYPE: fs
        GIGAPI_LAYERS_0_URL: "file:///data"
        GIGAPI_ENABLED: true
        GIGAPI_MERGE_TIMEOUT_S: 10
        GIGAPI_METADATA_TYPE: redis
        GIGAPI_METADATA_URL: redis://localhost:6379/0 
        
    - name: Run tests (redis + minio)
      continue-on-error: false
      run: |
        mkdir -p ./data-minio
        go test -v ./...
      env:
        GIGAPI_ROOT: "/data-minio"
        GIGAPI_LAYERS_0_NAME: default
        GIGAPI_LAYERS_0_TYPE: fs
        GIGAPI_LAYERS_0_URL: "file:///data"
        GIGAPI_LAYERS_0_TTL: 30s
        GIGAPI_LAYERS_1_NAME: s3
        GIGAPI_LAYERS_1_TYPE: s3
        GIGAPI_LAYERS_1_TTL: 0
        GIGAPI_LAYERS_1_URL: "s3://minio:9000/gigapi?secure=false&url-style=path"
        GIGAPI_LAYERS_1_AUTH_KEY: minioadmin
        GIGAPI_LAYERS_1_AUTH_SECRET: minioadmin
        GIGAPI_ENABLED: true
        GIGAPI_MERGE_TIMEOUT_S: 10
        GIGAPI_METADATA_TYPE: redis
        GIGAPI_METADATA_URL: redis://localhost:6379/0 
