name: Build-Go

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
    - run: go version     
    - name: Build
      run: |
        go mod tidy
        CGO_ENABLED=1 go build -o gigapi .
        ls -alFh gigapi
        strip gigapi
        ls -alFh gigapi
